@baseUrl=http://localhost:3000/api 
@resourceName=products
# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "title": "visual",
    "author": "code"
}

### 

# @name update
PATCH {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
    "title": "rest",
    "author": "client"
}

###

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/3
